# Generated by Django 5.1.3 on 2024-11-09 19:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "SCHEDULED"),
                            ("In Progress", "IN_PROGRESS"),
                            ("Completed", "COMPELTED"),
                            ("Failed", "FAILED"),
                        ],
                        default="Scheduled",
                        max_length=15,
                    ),
                ),
                ("failed_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "db_table": "task",
            },
        ),
    ]
